runtime: nodejs20 # Specify the Node.js version
env: standard
instance_class: F2 # Optional: Define the instance class

# Define the entry point for the application
entrypoint: npm start

automatic_scaling:
  min_instances: 1
